In [1]:
pip install -U fortran-magic

In [2]:
%reload_ext fortranmagic

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [3]:
import py_compile

In [4]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [5]:
assert ran_the_first_cell, "Oh noes!"

In [6]:
#assert ran_the_second_cell, "Oh yeees!"

In [7]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [8]:
m = [10, 'one', 3.1, 4, -5.0, "six"]
m

[10, 'one', 3.1, 4, -5.0, 'six']

In [9]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [10]:
first1 = m[0]
second1 = m[1]
print("first:", first1)
print("second:", second1)

first: 10
second: one


In [11]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [12]:
last1 = m[-1]
penultimate1 = m[-2]
print("last:", last1)
print("second to last:", penultimate1)

last: six
second to last: -5.0


In [13]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [14]:
sublist1 = m[1:3]
sublist1

['one', 3.1]

In [15]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [16]:
first_three1 = m[:3]
first_three1

[10, 'one', 3.1]

In [17]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [18]:
after_three1 = m[2:]
after_three1

[3.1, 4, -5.0, 'six']

In [19]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [20]:
m = ['s', 't', 'v', 'w', 'x', 'y', 'z']
m[1:7:2]

['t', 'w', 'y']

In [21]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [22]:
m[::-1]

['z', 'y', 'x', 'w', 'v', 't', 's']

In [23]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [24]:
m = [1, 2, 3, 4, 5]
print("Before:", m)
m.append('sexxx1')
print("After:", m)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'sexxx1']


In [25]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [26]:
m = [10, 20, 30, 40, 50]
[j * 2 for j in m]

[20, 40, 60, 80, 100]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [27]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [28]:
painters = {'Leonardo': 'Da Vinci', 'Claude': 'Monet', 'Vincent': 'Van Gogh'}
painters

{'Claude': 'Monet', 'Leonardo': 'Da Vinci', 'Vincent': 'Van Gogh'}

In [29]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [30]:
painters['Pablo'] = 'Picaso'
painters

{'Claude': 'Monet',
 'Leonardo': 'Da Vinci',
 'Pablo': 'Picaso',
 'Vincent': 'Van Gogh'}

In [31]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [32]:
del painters['Vincent']
painters

{'Claude': 'Monet', 'Leonardo': 'Da Vinci', 'Pablo': 'Picaso'}

In [33]:
# No slicing.
#philosophers['Bertrand':'Immanuel']

In [34]:
# No slicing.
#philosophers['Bertrand':'Immanuel']

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [35]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [36]:
c = [[10, 20, 30],
     [20, 30, 40],
     [50, 60, 70],
     [10, 10, 10]]

d = [[10, 20, 30, 40],
     [20, 30, 40, 50]]

In [37]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [38]:
def matmul1(C, D):
    """Multiply matrix A by matrix B."""
    rows_out = len(C)
    cols_out = len(D[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(D)):
                out[i][j] += C[i][k] * D[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [39]:
%%time

matmul(a, b)

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 45.5 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [40]:
matmul1(a, b)

[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [41]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.9476970425325443, 0.26813011159068834, 0.2597218919816583],
 [0.0359627898803051, 0.7871179718100185, 0.6991453564527386]]

In [42]:
import random
def random_matrix1(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix1(2, 3)
randm

[[0.7787427335314586, 0.7681453285787482, 0.2736910525084876],
 [0.3848821203492778, 0.7771033249369133, 0.13780491634800984]]

In [43]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 7.33 s, sys: 23.7 ms, total: 7.35 s
Wall time: 7.38 s


In [44]:
%%time
randa = random_matrix1(600, 100)
randb = random_matrix1(100, 600)
y = matmul1(randa, randb)

CPU times: user 7.37 s, sys: 23.1 ms, total: 7.39 s
Wall time: 7.43 s


In [45]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [46]:
def python_dot_product1(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [47]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [48]:
%%fortran
subroutine fortran_dot_product(xs, ys, result1)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result1
    
    result1 = sum(xs * ys)
end

In [49]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [50]:
list_data1 = [float(i) for i in range(100000)]
array_data1 = np.array(list_data1)

In [51]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 8.26 ms, sys: 0 ns, total: 8.26 ms
Wall time: 8.65 ms


333328333350000.0

In [52]:
%%time
python_dot_product1(list_data1, list_data1)

CPU times: user 13.6 ms, sys: 1.97 ms, total: 15.5 ms
Wall time: 18.3 ms


333328333350000.0

In [53]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 189 µs, sys: 5 µs, total: 194 µs
Wall time: 202 µs


333328333350000.0

In [54]:
%%time
fortran_dot_product(array_data1, array_data1)

CPU times: user 184 µs, sys: 0 ns, total: 184 µs
Wall time: 191 µs


333328333350000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [55]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [56]:
# Dynamic typing.
def mul_elemwise1(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise1([1, 2, 3, 6], [1, 2 + 0j, 3.0, 'five'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fivefivefivefivefivefive']

In [57]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [58]:
# Interpretation overhead.
source_code1 = 'a + b * c + a * b'
bytecode1 = compile(source_code1, '', 'eval')
import dis; dis.dis(bytecode1)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 LOAD_NAME                0 (a)
             12 LOAD_NAME                1 (b)
             14 BINARY_MULTIPLY
             16 BINARY_ADD
             18 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [59]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [60]:
data = np.array([5, 5, 6, 6])
data

array([5, 5, 6, 6])

In [61]:
data + data

array([10, 10, 12, 12])

In [62]:
data + data + data

array([15, 15, 18, 18])

In [63]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 0 ns, sys: 1.32 ms, total: 1.32 ms
Wall time: 3.05 ms


333328333350000.0

In [64]:
%%time
# Naive dot product
(array_data1 * array_data1).sum()

CPU times: user 0 ns, sys: 766 µs, total: 766 µs
Wall time: 1.39 ms


333328333350000.0

In [65]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 1.31 ms, sys: 3.01 ms, total: 4.31 ms
Wall time: 4.93 ms


333328333350000.0

In [66]:
%%time
# Built-in dot product.
array_data1.dot(array_data1)

CPU times: user 460 µs, sys: 0 ns, total: 460 µs
Wall time: 651 µs


333328333350000.0

In [67]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 184 µs, sys: 6 µs, total: 190 µs
Wall time: 198 µs


333328333350000.0

In [68]:
%%time
fortran_dot_product(array_data1, array_data1)

CPU times: user 199 µs, sys: 6 µs, total: 205 µs
Wall time: 213 µs


333328333350000.0

In [69]:
# Numpy won't allow us to write a string into an int array.
#data[0] = "foo"

In [70]:
# Numpy won't allow us to write a string into an int array.
#data[0] = "why not!"

In [71]:
# We also can't grow an array once it's created.
#data.append(3)

In [72]:
# We also can't grow an array once it's created.
#data.append(3)

In [73]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[5, 5],
       [6, 6]])

In [74]:
two_by_two1 = data.reshape(2, 2)
two_by_two1

array([[5, 5],
       [6, 6]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [75]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [76]:
arr = np.array([10, 20, 30, 40, 50, 60], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("==")
print("D:", arr.dtype)
print("S:", arr.shape)
print("S:", arr.strides)
print("D:", arr.data.tobytes())

Array:
[[10 20 30]
 [40 50 60]]
==
D: int16
S: (2, 3)
S: (6, 2)
D: b'\n\x00\x14\x00\x1e\x00(\x002\x00<\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [77]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
data1 = np.arange(20).reshape(4, 5)
data1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [80]:
data1 * data1

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [81]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [82]:
np.sqrt(data1)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [83]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [84]:
# Comparison operations
(data1 % 2) == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [85]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [86]:
# Boolean combinators.
((data1 % 3) == 0) & ((data1 % 4) == 0)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [87]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [88]:
data1 @ data1.T

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [89]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [90]:
sines1 = np.sin(np.linspace(0, 5.14, 10))
cosines1 = np.cos(np.linspace(0, 2.14, 10))
sines1

array([ 0.        ,  0.54056716,  0.90955924,  0.98985879,  0.75597887,
        0.28215256, -0.28122848, -0.75534809, -0.98972152, -0.90995905])

In [91]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [92]:
sines[1]

0.34185384854620343

In [93]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [94]:
sines[:2]

array([0.        , 0.34185385])

In [95]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [96]:
sines[1:]

array([0.34185385, 0.64251645, 0.86575984, 0.98468459, 0.98496101,
       0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [97]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [98]:
sines[::3]

array([0.        , 0.86575984, 0.8665558 , 0.00159265])

In [99]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [100]:
print("My_sines:\n", sines1)
print("sines > 0.5:\n", sines1 > 0.5)
print("sines[sines > 0.5]:\n", sines1[sines1 > 0.5])

My_sines:
 [ 0.          0.54056716  0.90955924  0.98985879  0.75597887  0.28215256
 -0.28122848 -0.75534809 -0.98972152 -0.90995905]
sines > 0.5:
 [False  True  True  True  True False False False False False]
sines[sines > 0.5]:
 [0.54056716 0.90955924 0.98985879 0.75597887]


In [101]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [102]:
print(sines1)
sines1[[0, 2, 7]]

[ 0.          0.54056716  0.90955924  0.98985879  0.75597887  0.28215256
 -0.28122848 -0.75534809 -0.98972152 -0.90995905]


array([ 0.        ,  0.90955924, -0.75534809])

In [103]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [104]:
unsorted_data1 = np.array([10, 30, 20, 120, -10, 50, 20])

In [105]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [106]:
sort_indices1 = np.argsort(unsorted_data1)
sort_indices1

array([4, 0, 2, 6, 1, 5, 3])

In [107]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [108]:
unsorted_data1[sort_indices1]

array([-10,  10,  20,  20,  30,  50, 120])

In [109]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [110]:
market_caps1 = np.array([120, 60, 100, 50, 60])
assets1 = np.array(['S', 'T', 'U', 'V', 'W'])

In [111]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [112]:
sort_by_mcap1 = np.argsort(market_caps1)
assets[sort_by_mcap1]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [113]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [114]:
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [115]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


In [116]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [117]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
data = np.arange(20).reshape(4, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [119]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [120]:
data[:1, :1]

array([[0]])

In [121]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [122]:
data[:3, [0, -1]]

array([[ 0,  4],
       [ 5,  9],
       [10, 14]])

In [123]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [124]:
data[(data[:, 0] % 3) == 0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [125]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [126]:
def variance1(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [127]:
variance(np.random.standard_normal(1000))

0.976117282449133

In [128]:
variance(np.random.standard_normal(10))

1.1274798509777189

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [129]:
data = np.arange(30)
data.mean()

14.5

In [130]:
data1 = np.arange(15)
data1.mean()

7.0

- ...but we can do more interesting things with multi-dimensional arrays.

In [131]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [132]:
data1 = np.arange(32).reshape(4, 8)
data1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [133]:
data.mean()

14.5

In [134]:
data1.mean()

15.5

In [135]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [136]:
data1.mean(axis=0)

array([12., 13., 14., 15., 16., 17., 18., 19.])

In [137]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [138]:
data1.mean(axis=1)

array([ 3.5, 11.5, 19.5, 27.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [139]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [140]:
row1 = np.array([2, 5, 6, 7])
column1 = np.array([[5], [6], [7]])
print("Row:\n", row1, sep='')
print("Column:\n", column1, sep='')

Row:
[2 5 6 7]
Column:
[[5]
 [6]
 [7]]


In [141]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [142]:
row1+ column1

array([[ 7, 10, 11, 12],
       [ 8, 11, 12, 13],
       [ 9, 12, 13, 14]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [143]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [144]:
print("Data:\n", data1, sep='')
print("Mean:\n", data1.mean(axis=0), sep='')
print("Data - Mean:\n", data1 - data1.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
Mean:
[12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-12. -12. -12. -12. -12. -12. -12. -12.]
 [ -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.]
 [  4.   4.   4.   4.   4.   4.   4.   4.]
 [ 12.  12.  12.  12.  12.  12.  12.  12.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [145]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [146]:
s1 = pd.Series(index=['w', 'x', 'y', 'z', 't'], data=[10, 20, 30, 40, 50])
s1

w    10
x    20
y    30
z    40
t    50
dtype: int64

In [147]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [148]:
print("The index is:", s1.index)
print("The values are:", s1.values)

The index is: Index(['w', 'x', 'y', 'z', 't'], dtype='object')
The values are: [10 20 30 40 50]


In [149]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [150]:
s1.iloc[0]

10

In [151]:
# ... or by label.
s.loc['a']

1

In [152]:
s1.loc['w']

10

In [153]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [154]:
s1.iloc[:3]

w    10
x    20
y    30
dtype: int64

In [155]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [156]:
s1.loc[:'x']

w    10
x    20
dtype: int64

In [157]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [158]:
s1.iloc[[0, -1]]

w    10
t    50
dtype: int64

In [159]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [160]:
s1.loc[s1 > 1]

w    10
x    20
y    30
z    40
t    50
dtype: int64

In [161]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [162]:
other_s1 = pd.Series({'w': 10.0, 'x': 20.0, 'y': 30.0, 'z': 40.0})
other_s1

w    10.0
x    20.0
y    30.0
z    40.0
dtype: float64

In [163]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [164]:
s1 + other_s1

t     NaN
w    20.0
x    40.0
y    60.0
z    80.0
dtype: float64

In [165]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [166]:
(s1 + other_s1).fillna(0.0)

t     0.0
w    20.0
x    40.0
y    60.0
z    80.0
dtype: float64

In [167]:
from pandas_datareader import data

In [169]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [170]:
aapl1 = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl1.head()

FileNotFoundError: ignored

In [171]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [172]:
#Same error
aapl1.iloc[:2, :2]

NameError: ignored

In [173]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

In [174]:
aapl1.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [175]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [176]:
aapl1.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [177]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

NameError: ignored

In [178]:
aapl1.drop('Volume', axis=1).resample('2W').max().plot();

NameError: ignored

In [179]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

NameError: ignored

In [180]:
aapl1['Close'].pct_change().ewm(span=30).std().plot();

NameError: ignored

# "Real World" Data

In [181]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

ModuleNotFoundError: ignored

In [182]:
avocados1 = read_avocadata('2009', '2011')
avocados1.head()

NameError: ignored

In [183]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

NameError: ignored

In [184]:
avocados1.dtypes

NameError: ignored

In [185]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

NameError: ignored

In [186]:
hass1 = avocados1[avocados1.Variety == 'HASS']
hass1.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

NameError: ignored

In [188]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [190]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [189]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

NameError: ignored

In [191]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

NameError: ignored

In [192]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

NameError: ignored

In [193]:
spread_correlation1 = organic_spread_by_region(hass).corr()
spread_correlation1

NameError: ignored

In [194]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

NameError: ignored

In [195]:
grid1 = sns.clustermap(spread_correlation, annot=True)
fig1 = grid1.fig1
axes1 = fig1.axes1
ax1 = axes1[2]
ax1.set_xticklabels(ax.get_xticklabels(), rotation=45);

NameError: ignored

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!